name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: '0 18 * * sun'

jobs:
  test:
    name: ${{ matrix.image }} sonar ${{ matrix.sonar_scanner_version }}
    runs-on: ubuntu-22.04
    env:
      docker_namespace: ghcr.io/diodonfrost/docker-ansible
    strategy:
      fail-fast: false
      matrix:
        image:
          - centos:stream9
          - centos:stream8
          - fedora:38
          - fedora:37
          - fedora:36
          - fedora:35
          - fedora:34
          - fedora:33
          - ubuntu:22.04
          - ubuntu:18.04
          - debian:11
          - debian:10
          - oraclelinux:8
          - oraclelinux:7
          - amazonlinux:2023
          - amazonlinux:2
          - archlinux:latest
          - gentoo:latest
        sonar_scanner_version:
          - latest
          - 3.3.0.1492

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Molecule
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Test Ansible role
        run: molecule test
        env:
          namespace: ${{ env.docker_namespace }}
          image: ansible-${{ matrix.image }}
          sonar_scanner_version: ${{ matrix.sonar_scanner_version }}

      - name: Test Ansible role with check_mode enable
        run: molecule check
        env:
          namespace: ${{ env.docker_namespace }}
          image: ansible-${{ matrix.image }}
          sonar_scanner_version: ${{ matrix.sonar_scanner_version }}
